name: PHP tests on alpine

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: php:8.2-fpm-alpine

    steps:
      - name: Checkout code
        run: |
          apk add wget
          wget https://github.com/kiwilan/php-filelist/archive/refs/heads/main.zip
          unzip main.zip
          mv php-filelist-main/* .
          rm -rf php-filelist-main
          rm main.zip
          ls

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install scout-seeker
        run: |
          apk add rustup
          apk add build-base
          cargo install scout-seeker

      - name: Install dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
          composer install

      - name: Execute tests
        run: |
          ls
          vendor/bin/pest --ci
