name: PHP tests on alpine

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     services:
#       docker:
#         image: php:8.2-alpine
#         options: --entrypoint ""

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up PHP
#         run: |
#           docker run --rm -v ${{ github.workspace }}:/app -w /app php:8.2-alpine php -v

#       - name: Install dependencies
#         run: |
#           docker run --rm -v ${{ github.workspace }}:/app -w /app php:8.2-alpine composer install

#       - name: Run tests
#         run: |
#           docker run --rm -v ${{ github.workspace }}:/app -w /app php:8.2-alpine vendor/bin/pest

jobs:
  test:
    runs-on: ubuntu-latest
    container: php:8.2-fpm-alpine

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: none
          coverage: none

      - name: Install dependencies
        run: |
          composer install

      - name: Run tests
        run: |
          vendor/bin/pest
