name: PHP tests on alpine

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: php:8.2-fpm-alpine

    steps:
      - name: Checkout code
        run: |
          apk add git
          git clone https://github.com/kiwilan/php-filelist.git

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install scout-seeker
        run: |
          apk add rustup
          apk add build-base
          cargo install scout-seeker

      - name: Install dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
          cd php-filelist && composer install

      - name: Execute tests
        run: |
          cd php-filelist && vendor/bin/pest --ci
